# This file will be included by the Makefile under the project directory.

FLOAT_O := $(FLOAT:.a=.o)
FLOAT_VFPRINTF_O := $(dir $(FLOAT))FLOAT_vfprintf.o

FLOAT_A_OBJ := $(FLOAT_O) $(FLOAT_VFPRINTF_O)

FLOAT_CFLAGS := -MMD -Wall -Werror -c -m32 -O2 \
			-fno-if-conversion -fno-builtin -I$(LIB_COMMON_DIR)
FLOAT_VFPRINTF_CFLAGS := $(FLOAT_CFLAGS) -fno-stack-protector \
			-D_FORTIFY_SOURCE=0

$(FLOAT): $(FLOAT_A_OBJ)
	ar r $@ $^

$(FLOAT_O): lib-common/FLOAT/FLOAT.c
	$(call make_command, $(CC), $(FLOAT_CFLAGS), cc $@, $<)

$(FLOAT_VFPRINTF_O): lib-common/FLOAT/FLOAT_vfprintf.c
	$(call make_command, $(CC), $(FLOAT_VFPRINTF_CFLAGS), cc $@, $<)

-include $(FLOAT_A_OBJ:.o=.d)

